name: testback deployment

on:
  push:
    branches: ["main"]

jobs:
  bulid:
    name: testback bulid & deploy
    runs-on: ubuntu-latest

    steps:
      - name: github action
        run: echo "github action"

      - name: hello
        run: echo "hello world"

      - name: git hello
        run: |
          echo "git hello"
          echo "hello github action"

      - name: github action
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: github secret
        run: |
          echo ${{ secrets.MY_HOBBY }}
