name: testback deployment

on:
  push:
    branches:
      - main

jobs:
  bulid:
    name: testback bulid & deploy
    runs-on: ubuntu-latest

  steps:
    - name: github action
      run: echo "github action"
